version: '3.8'

services:
  main:
    container_name: "${APP_NAME}-main"
    build:
      dockerfile: Dockerfile
      context: .
      target: development
      args:
        # Enabling Docker Buildkit
        DOCKER_BUILDKIT: 1
    volumes:
      # Allows changes made in the project directory to be accessed by the container and persist
      - ./src:/usr/src/app/src
      # Ensuring that the container manages the node_modules folder rather than synchronizes it with the host machine
      - /usr/src/app/node_modules
    ports:
      # Exposing application port
      - ${APP_PORT_EXTERNAL}:${APP_PORT}
      # Exposing NestJS debugging port
      - 9229:9229
      # Exposing Prisma Studio port
      - 5555:5555
    command: yarn run start:dev
    environment:
      # To configure timezone for the container
      TZ: "${APP_TIMEZONE}"
      # To enable hot reload on docker for windows (WSL) in combination with a adjust on tsconfig.build.json file
      WATCHPACK_POLLING: true
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nestjs-comics-characters-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: "${APP_NAME}-mysql"
    build: .docker/mysql
    platform: linux/amd64
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./.docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - nestjs-comics-characters-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  nestjs-comics-characters-network:
    driver: bridge