export enum RelationshipTypeEnum {
  mother = 1, // Mãe
  father = 2, // Pai
  son = 3, // Filho
  daughter = 4, // Filha
  brother = 5, // Irmão
  sister = 6, // Irmã
  grandmother = 7, // Avó
  grandfather = 8, // Avô
  grandson = 9, // Neto
  granddaughter = 10, // Neta
  aunt = 11, // Tia
  uncle = 12, // Tio
  niece = 13, // Sobrinha
  nephew = 14, // Sobrinho
  great_grandmother = 15, // Bisavó
  great_grandfather = 16, // Bisavô
  great_grandson = 17, // Bisneto
  great_granddaughter = 18, // Bisneta
  great_aunt = 19, // Tia Avó
  great_uncle = 20, // Tio Avô
  cousin = 21, // Primo / Prima
  wife = 22, // Esposa
  husband = 23, // Marido
  mother_in_law = 24, // Sogra
  father_in_law = 25, // Sogro
  brother_in_law = 26, // Cunhado
  sister_in_law = 27, // Cunhada
  stepfather = 28, // Padrasto
  stepmother = 29, // Madrasta
  stepson = 30, // Enteado
  stepdaughter = 31, // Enteada
  godfather = 32, // Padrinho
  godmother = 33, // Madrinha
  godson = 34, // Afilhado
  goddaughter = 35, // Afilhada
  clone = 36, // Clone
}
