export enum RelationshipTypeStringEnum {
  mother = 'mother', // Mãe
  father = 'father', // Pai
  son = 'son', // Filho
  daughter = 'daughter', // Filha
  brother = 'brother', // Irmão
  sister = 'sister', // Irmã
  grandmother = 'grandmother', // Avó
  grandfather = 'grandfather', // Avô
  grandson = 'grandson', // Neto
  granddaughter = 'granddaughter', // Neta
  aunt = 'aunt', // Tia
  uncle = 'uncle', // Tio
  niece = 'niece', // Sobrinha
  nephew = 'nephew', // Sobrinho
  great_grandmother = 'great-grandmother', // Bisavó
  great_grandfather = 'great-grandfather', // Bisavô
  great_grandson = 'great-grandson', // Bisneto
  great_granddaughter = 'great-granddaughter', // Bisneta
  great_aunt = 'great-aunt', // Tia Avó
  great_uncle = 'great-uncle', // Tio Avô
  cousin = 'cousin', // Primo / Prima
  wife = 'wife', // Esposa
  husband = 'husband', // Marido
  mother_in_law = 'mother-in-law', // Sogra
  father_in_law = 'father-in-law', // Sogro
  brother_in_law = 'brother-in-law', // Cunhado
  sister_in_law = 'sister-in-law', // Cunhada
  stepfather = 'stepfather', // Padrasto
  stepmother = 'stepmother', // Madrasta
  stepson = 'stepson', // Enteado
  stepdaughter = 'stepdaughter', // Enteada
  godfather = 'godfather', // Padrinho
  godmother = 'godmother', // Madrinha
  godson = 'godson', // Afilhado
  goddaughter = 'goddaughter', // Afilhada
  clone = 'clone', // Clone
}
