### Variables
@baseUrl=http://localhost:3000/api/v1
@accept=application/json
@contentType=application/json

### POST auth login
POST {{baseUrl}}/auth/login
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "email": "default@app.com",
    "password": "defaultpassword"
}