### Variables
@baseUrl=http://localhost:3000/api/v1
@accept=application/json
@contentType=application/json

### POST characters
POST {{baseUrl}}/characters
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "name": "a",
    "alignmentId": 1
}

### GET character
GET {{baseUrl}}/characters/1
Accept: {{accept}}
Content-Type: {{contentType}}

### GET character
GET {{baseUrl}}/characters/19
Accept: {{accept}}
Content-Type: {{contentType}}