### Variables
@baseUrl=http://localhost:3000/api/v1
@accept=application/json
@contentType=application/json

### POST users
POST {{baseUrl}}/users
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "name": "Generic App 1",
    "email": "generic_1@app.com",
    "password": "iamapassword"
}

### PATCH users/:id
PATCH {{baseUrl}}/users/2
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "name": "Generic App TTP1"
}

### GET users/:id
GET {{baseUrl}}/users/2
Accept: {{accept}}
Content-Type: {{contentType}}